/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminTable: typeof import('./components/AdminTable.vue')['default']
    Banner: typeof import('./components/Banner.vue')['default']
    Featured: typeof import('./components/Featured.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Login: typeof import('./components/Login.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    ProductGrid: typeof import('./components/ProductGrid.vue')['default']
    Profile: typeof import('./components/Profile.vue')['default']
    Register: typeof import('./components/Register.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
